# Generated by Django 5.2.6 on 2025-10-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=10)),
            ],
        ),
    ]
