# Generated by Django 5.2.6 on 2025-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='colour',
            new_name='bg_colour',
        ),
        migrations.AddField(
            model_name='route',
            name='text_colour',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
